sudo: true
language: node
os:
- linux
- osx
osx_image: xcode8
cache: yarn
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn; fi
install:
  - yarn
script:
  - make lint
  - make build
notifications:
  email: false
