version: 1.0.{build}
init:
- ps: Install-Product node 8.6.0 x64
environment:
  CL: -DDELAYIMP_INSECURE_WRITABLE_HOOKS
install:
- ps: Start-FileDownload 'https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe'
- rustup-init.exe -y
- SET PATH=%PATH%;%USERPROFILE%\.cargo\bin
- rustc -V
- cargo -V
- ps: git submodule update --init --recursive; true
- ps: npm install; true
- ps: npm install -g eslint eslint-plugin-mocha
build_script:
- ps: npm run build; true
test_script:
- ps: eslint .
- ps: npm test
