version: 1.0.{build}
init:
- ps: Install-Product node 7.4.0 x64
- ps: choco install make jq
environment:
  CL: -DDELAYIMP_INSECURE_WRITABLE_HOOKS
build_script:
- ps: yarn
- ps: make build
test_script:
- ps: make lint
before_deploy:
- ps: make pack
- ps: make winstaller
artifacts:
- path: deplug-win-amd64.exe
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: 5xfEThlejgLcJhJS3rNfbbvFPDyuRy+wVgC0/KrbMiWycAYQej7GhAbCVvSneLoT
  artifact: deplug-win-amd64.exe
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
