version: 1.0.{build}
init:
- ps: Install-Product node 8.6.0 x64
- ps: choco install make
environment:
  CL: -DDELAYIMP_INSECURE_WRITABLE_HOOKS
install:
- ps: git submodule update --init --recursive; true
- ps: npm install; true
build_script:
- ps: make build; true
test_script:
- ps: make lint
- ps: make test
after_test:
- ps: npm install -g npm
- ps: npm install -g modclean
- ps: modclean --run
- ps: node scripts/pack.js
- ps: node scripts/winstaller.js
- ps: mv out/DeplugSetup.exe out/deplug-win-amd64.exe
artifacts:
- path: out/deplug-win-amd64.exe
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: 5xfEThlejgLcJhJS3rNfbbvFPDyuRy+wVgC0/KrbMiWycAYQej7GhAbCVvSneLoT
  artifact: out/deplug-win-amd64.exe
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
