[package]
name = "pcap-reader"
version = "0.1.0"

[dependencies]
serde = "1"
serde_json = "1"
serde_derive = "1"
lazy_static = "1"
genet-abi = { path = "../../../../lib/genet-abi" }
genet-sdk = { path = "../../../../lib/genet-sdk" }

[lib]
crate-type = ["cdylib"]