[package]
name = "ipv6"
version = "0.1.0"
authors = ["Ron Hashimoto <mail@h2so5.net>"]

[lib]
name = "main"
crate-type = ["cdylib"]
path = "src/ipv6.rs"

[dependencies]
libc = "*"
byteorder = "1"
plugkit = { path = "../../plugkit/plugkit-rust" }
