[package]
name = "pcap-layer"
version = "0.1.0"
authors = ["Ron Hashimoto <mail@h2so5.net>"]
edition = "2018"

[lib]
name = "pcap_layer"
crate-type = ["cdylib"]

[dependencies]
genet-sdk = "0.5.0"
genet-derive = { path = "../../../genet-derive" }
