[package]
name = "genet-derive"
description = "genet SDK derives"
license = "MIT"
version = "0.5.0"
authors = ["Ron Hashimoto <mail@h2so5.net>"]

[dependencies]
proc-macro2 = "0.4"
quote = "0.6.3"
syn = "0.15"
Inflector = "0.11"
genet-abi = { path = "../genet-abi" }

[lib]
proc-macro = true