[package]
name = "genet-sdk"
description = "genet SDK"
license = "MIT"
version = "0.5.0"
authors = ["Ron Hashimoto <mail@h2so5.net>"]
edition = "2018"

[dependencies]
bincode = "1"
byteorder = "1"
genet-abi = "0.5.0"
serde = "1"
serde_derive = "1"
