[package]
name = "genet-reader"
version = "0.1.0"

[dependencies]
serde = "1"
serde_json = "1"
serde_derive = "1"
bincode = "1"
genet-sdk = "0.3.0"
genet-format = { path = "../format" }

[lib]
name = "reader"
crate-type = ["cdylib"]
