[package]
name = "pcap-writer"
version = "0.1.0"

[dependencies]
serde = "1"
serde_json = "1"
serde_derive = "1"
lazy_static = "1"
byteorder = "1"
genet-sdk = "0.2.0"

[lib]
name = "writer"
crate-type = ["cdylib"]
