[package]
name = "pcap-writer"
version = "0.1.0"
edition = "2018"

[dependencies]
byteorder = "1"
genet-derive = { path = "../../../genet-derive" }
genet-sdk = "0.5.0"

[lib]
crate-type = ["rlib", "cdylib"]
name = "writer"
