[package]
name = "genet-abi"
description = "genet ABI definitions"
license = "MIT"
version = "0.5.0"
authors = ["Ron Hashimoto <mail@h2so5.net>"]

[dependencies]
libc = "0.2"
lazy_static = "1"
fnv = "1"
parking_lot = "0.6"
serde = "1"
serde_json = "1"
serde_derive = "1"